#
# valipop - <https://github.com/stacs-srg/valipop>
# Copyright © 2025 Systems Research Group, University of St Andrews (graham.kirby@st-andrews.ac.uk)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

services:
  base:
    image: valipop-base
    build:
      context: .
      dockerfile: docker/Dockerfile
  model:
    image: valipop
    build:
      context: .
      dockerfile: docker/model/Dockerfile
      # mvn package needs to be able to open more files
    volumes:
      - "./src/main/resources/valipop/config:/app/src/main/resources/valipop/config"
      - "./src/main/resources/valipop/inputs/:/app/src/main/resources/valipop/inputs/"
      - "./results/:/app/results/"
  master:
    image: valipop-master
    build:
      context: .
      dockerfile: docker/cluster/master/Dockerfile
    ports:
      - 8080:8080
      - 23177:23177
    network_mode: "host"
  worker:
    image: valipop-worker
    build:
      context: .
      dockerfile: docker/cluster/worker/Dockerfile
    volumes:
      - "./src/main/resources/valipop/inputs/:/app/src/main/resources/valipop/inputs/"
    network_mode: "host"
    
  factor-search:
    image: valipop-factor-search
    build:
      context: .
      dockerfile: docker/factor-search/Dockerfile
    volumes:
      - "./src/main/resources/valipop/config:/app/src/main/resources/valipop/config"
      - "./src/main/resources/valipop/inputs/:/app/src/main/resources/valipop/inputs/"
      - "./results/:/app/results/"
    ports:
      - 5055:5055
    network_mode: "host"
    