name: Maven Build and Test

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      maven-target:
        required: true
        type: string
      upload-dependencies:
        required: false
        type: boolean
        default: false

env:
  JDK_VERSION: '21'
  JDK_DISTRIBUTION: 'corretto'
  R_VERSION: '4.4.3'

jobs:
  build-and-test:
    permissions:
      contents: write
    runs-on: ${{ inputs.platform }}

    steps:
    - name: Check out project
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683                                        # @v4.2.2

    - name: Set up JDK
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00                                      # @v4.7.1
      with:
        java-version: ${{ env.JDK_VERSION }}
        distribution: ${{ env.JDK_DISTRIBUTION }}
        cache: 'maven'

    - name: Install R
      uses: r-lib/actions/setup-r@6b49fefb2846ed3e5e6e58366e7f7dfe01377f02                                # 29/04/2025
      with:
        r-version: ${{ env.R_VERSION }}

    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@6b49fefb2846ed3e5e6e58366e7f7dfe01377f02                   # 29/04/2025
      with:
        extra-packages: any::geepack

    - name: Build and test with Maven
      run: mvn -B package

    - name: Upload dependencies
      if: inputs.upload-dependencies
      uses: advanced-security/maven-dependency-submission-action@v4
