# This checks every 24 hours for new commits, and runs a test build if there are any.

name: Build and test (scheduled)

on:
  schedule:
    - cron: "15 02 * * *"
  workflow_dispatch:

jobs:
  build-and-test-linux:
    name: Build and test (Linux)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683                                        # @v4.2.2

      - name: Count recent commits
        run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_ENV

      - name: Build and run tests if there were recent changes
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        uses: ./.github/actions/build-and-test
        with:
          maven-target: 'test'
