name: Build and Deploy (Scheduled)

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

concurrency:
  group: "build deploy"
  cancel-in-progress: true

jobs:
  build-and-test-linux:
    name: Build and test (Linux)
    permissions:
      contents: write
    uses: ./.github/workflows/build-and-test.yml
    with:
      platform: ubuntu-latest
      maven-target: test
