# This checks every 24 hours for new commits, and runs a test build if there are any.

name: Build and test (scheduled)

on:
  schedule:
    - cron: "15,45 * * * *"
  workflow_dispatch:

concurrency:
  group: "build deploy"
  cancel-in-progress: true

jobs:
  build-and-test-linux:
    name: Build and test (Linux)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683                                        # @v4.2.2

      - name: Count recent commits
        run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '30 minutes ago' | wc -l)" >> $GITHUB_ENV

      - name: Build and test if there are recent changes
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        uses: ./.github/workflows/build-and-test.yml
        with:
          platform: ubuntu-latest
          maven-target: test
