# All jobs defined within single workflow file to allow control of job concurrency.
# Actions bind to specific action commits to reduce risk of action repos being compromised.defaults:
# It would be nice to define the commit hashes and version numbers as environment variables to
# reduce repetition, but actions can't be resolved dynamically.

name: Build and Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: "build deploy"
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683                                        # @v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00                                      # @v4.7.1
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Install R
        uses: r-lib/actions/setup-r@6b49fefb2846ed3e5e6e58366e7f7dfe01377f02                                # 29/04/2025
        with:
          r-version: '4.4.2'

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@6b49fefb2846ed3e5e6e58366e7f7dfe01377f02                   # 29/04/2025
        with:
          extra-packages: any::geepack

      - name: Build and test with Maven
        run: mvn -B package --file pom.xml
